#!/bin/sh

## application partition name
partname="rootfs"
## supported partition type list
parttype="jffs2 squashfs"
## default mtd device
mtddev="/dev/mtdblock4"
## mount point
appmnt="/apps"

mtdnr=$(grep -E "\"${partname}\"" /proc/mtd \
      | grep -E -o '^mtd[0-9]{1,2}' \
      | cut -b 4-)

if [ x"$mtdnr" != "x" ]; then
  mtddev="/dev/mtdblock${mtdnr}"
fi

if ! [ -d ${appmnt} ]; then
  mkdir -p ${appmnt}
fi

## try to mount the apps partition
mount_ok=no
for t in ${parttype}; do
  if mount -t ${t} ${mtddev} ${appmnt} 2>/dev/null; then
    mount_ok=yes
    break
  fi
done

## run etc/rc script in this partition
init_ok=no
if [ -x ${appmnt}/etc/rc ]; then
  if ${appmnt}/etc/rc; then
    init_ok=true
  fi
fi

if [ x"$mount_ok" != "xyes" -o x"$init_ok" != "xyes" ]; then
  echo -e "\033[31;1mENTER DOWNLOAD MODE\033[0m"
  ## start tftp server to upgrade the firmware
  /usr/bin/udpsvd -vE 0 69 /usr/bin/tftpd -c /var/cache/firmware &
  exit 1
fi
